name: Build

on:
  push:
    branches:
      - "master"
    tags:
      - "v*"
  pull_request:
    branches:
      - "master"
  schedule:
    - cron: "21 12 * * 1"
  workflow_dispatch:

env:
  DOCKERHUB_SLUG: sparanoid/php-fpm
  GHCR_SLUG: ghcr.io/sparanoid/php-fpm

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8-fpm, 8.3-fpm, 8.2-fpm, 8.1-fpm]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate current image prefix
        id: prefix
        # Remove unwanted `-fpm` suffix from base image
        run: |
          prefix=$(echo ${{ matrix.php }} | sed 's/-fpm//g')
          echo $prefix
          echo "ref=$prefix" >> $GITHUB_OUTPUT

      - name: Generate latest image tag
        id: tag
        # The ' ' is the tricky part to unset prefix parameter
        run: |
          echo "ref=${{ matrix.php == '8-fpm' && ' ' || format('{0}-', steps.prefix.outputs.ref) }}" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKERHUB_SLUG }}
            ${{ env.GHCR_SLUG }}
          flavor: |
            prefix=${{ matrix.php == '8-fpm' && ' ' || format('{0}-', steps.prefix.outputs.ref) }},onlatest=true
          tags: |
            type=edge,prefix=${{ steps.tag.outputs.ref }}
            type=schedule,prefix=${{ steps.tag.outputs.ref }}
            type=ref,event=branch,prefix=${{ steps.tag.outputs.ref }}
            type=ref,event=pr,prefix=${{ steps.tag.outputs.ref }}
            type=semver,pattern={{version}},prefix=${{ steps.tag.outputs.ref }}
            type=semver,pattern={{major}}.{{minor}},prefix=${{ steps.tag.outputs.ref }}
            type=semver,pattern={{major}},prefix=${{ steps.tag.outputs.ref }}
            type=sha,prefix=${{ steps.tag.outputs.ref }}sha-

      - name: Build and push
        uses: docker/bake-action@v5
        env:
          BASE_TAG: ${{ matrix.php }}
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          targets: build-all
          push: ${{ github.event_name != 'pull_request' }}
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max

      - name: Check manifest
        if: github.event_name != 'pull_request'
        run: |
          docker buildx imagetools inspect ${{ env.DOCKERHUB_SLUG }}:${{ steps.meta.outputs.version }}
          docker buildx imagetools inspect ${{ env.GHCR_SLUG }}:${{ steps.meta.outputs.version }}

      - name: Inspect image
        if: github.event_name != 'pull_request'
        run: |
          docker pull ${{ env.DOCKERHUB_SLUG }}:${{ steps.meta.outputs.version }}
          docker image inspect ${{ env.DOCKERHUB_SLUG }}:${{ steps.meta.outputs.version }}
          docker pull ${{ env.GHCR_SLUG }}:${{ steps.meta.outputs.version }}
          docker image inspect ${{ env.GHCR_SLUG }}:${{ steps.meta.outputs.version }}
